### ISSUE TITLE
可以考虑新增 hoas 例子

### ISSUE THREAD

**Issue by ice1000** [lsby/ts_adt_tutorial#1]
```haskell
data HOAS
 = Lam (HOAS -> HOAS)
 | App HOAS HOAS
```

这个好。

**Comment by lsby** [comment]
哇哦,大佬好!
没..没太明白啥意思, HOAS我的理解就是允许使用函数来描述语法规则.
但是和ADT有啥关系呢, 虽然确实可以用ADT表示这个.
用ADT分析这个类型的大小吗, 我试了一下没成功...求大佬指导QwQ

**Comment by ice1000** [comment]
这其实是个反例，看起来特别特别像是一个代数数据类型（因为使用 Haskell 的 data 语法定义），实际上并不「代数」，因为它不是由 polynomial functor 生成的。这个类型应该没有办法分析大小，因为部分值没有 normal form。

然后我在学 Haskell 的时候曾经长期认为这个类型是代数数据类型，不像你知道这么多 😂

**Comment by lsby** [comment]
啊...我只是看了下wiki和几个视频, 觉得差不多了解了就记录一下, 没有深究严格的定义.
顺着关键词查了一下, 查到了[这个问题](https://proofassistants.stackexchange.com/questions/879/what-is-an-algebraic-data-type), 虽然数学部分还看不懂, 但是结论大概了解了.
感谢大佬指点w

**Comment by ice1000** [comment]
草 你人肉我

**Comment by lsby** [comment]
hhhhhhhh没有没有, 只是查`polynomial functor`然后找到了[知乎](https://www.zhihu.com/question/24460419/answer/2387031599), 然后就顺着找到了...
不过大大很有名啊, 经常能见到, 看到这个issue的时候把我震惊到了...

**Comment by ice1000** [comment]
我在 echo.js 的 discord 里顺藤摸瓜过来的，但是你不在那个 discord，而且那个里面说话的人也很少😂

**Comment by lsby** [comment]
??????
我们的播客居然传播的这么广吗
是那期函数式编程吗, 天哪这么幼稚的内容被大大听到简直...
那之后我又学了类型系统, 这是简单的[笔记](https://github.com/lsby/Types-and-Programming-Languages-Note), 现在在看idris, 快看完了(证明的部分还没看), 作为编程语言的话我非常喜欢, 几乎可以随心所欲的用类型约束任何事了, 可以说非常理想, 最近写着玩的代码都在用idris.
接下来应该看什么呢, agda? coq? 还是什么书? 有什么建议吗QwQ
我一般用QQ, discord上啥也没有挂着没啥用...我以为没几个人会听我们播客, 听的话应该也是QQ人多一点🙈

**Comment by ice1000** [comment]
我没看到群号……是我认识的一个做代数几何的数学巨佬给我发的 echo.js 的链接。我其实没听，我就看了你们的网页里的介绍，唯一指向的链接就是这个仓库，感觉十分牛逼，这个 issue 相当于是打个招呼。🤣

编程语言的话，要不要试试 https://www.aya-prover.org/guide/install.html 呢

**Comment by lsby** [comment]
太..太怪了, 明明我们谈的都是些没营养的东西...感觉也没几个人听啊 能吸引到这么多巨佬是怎么回事..(好奇那个巨佬是怎么评价的
QQ群也不用加...也没几个人, 当然就更没啥人说话...(但是要加个QQ吗

我之前看到过Aya, 好像之前还看到过你们在招人(?), 找不到了, 也许是我的幻觉...
之前的印象是完全没有文档也不知道怎么用...
现在好像依然没有文档..

**Comment by ice1000** [comment]
> 我之前看到过Aya, 好像之前还看到过你们在招人(?), 找不到了, 也许是我的幻觉...
> 之前的印象是完全没有文档也不知道怎么用...
> 现在好像依然没有文档..

可以看代码例子，基本上跟 Idris Agda 那些差不多。特性还在大改，现在跟早期版本基本不是同一个语言。我比较怕又大改，所以就没写文档。不过现在应该可以写一些了，等我们文学编程模式就开搞。

**Comment by ice1000** [comment]
README 里我记得有几个链接，有一个红黑树的和一个自然数性质证明的可以看看😂

**Comment by ice1000** [comment]
> 好奇那个巨佬是怎么评价的

只是发了个链接，艾特了一下我 🤣

**Comment by lsby** [comment]
啊我大概看了下例子, 有些语法看不懂😂
好像类型系统差不多了? 除了好像没看到类型类...
然后还看到多层宇宙和自动推断顺序, 比idris强(
FFI有吗, 说不定我可以试着用用了www
另外我是中文编程怪, 希望不要有奇怪的"必须用大写字母/小写字母开头"的规定233

**Comment by ice1000** [comment]
> 好像类型系统差不多了? 除了好像没看到类型类...

类型类没做。我觉得这个语言特性是错的，在考虑实现 Arend class 那样的功能。

> 然后还看到多层宇宙和自动推断顺序, 比idris强(

Idris 我记得也有多层宇宙吧？我们这个多层宇宙是非常简单的……

> 另外我是中文编程怪, 希望不要有奇怪的"必须用大写字母/小写字母开头"的规定233

要不是嫌维护麻烦，本来打算做中文关键字的 alternative lexer 的。我们小部分关键字均有 unicode 代替版，函数名可以使用几乎所有 Unicode。不过我最近打算进行一些限制，至少应该禁止零宽字符和 unicode 空格等

**Comment by ice1000** [comment]
> 啊我大概看了下例子, 有些语法看不懂😂

讲讲？

**Comment by ice1000** [comment]
> 我觉得这个语言特性是错的

解释一下：比如 `Semigroup Int` 你觉得里面的操作是加法还是乘法呀

**Comment by lsby** [comment]
> Idris 我记得也有多层宇宙吧？

idris1是多层宇宙, 但是不允许自己指定, 是他内部管理的.
[idris2](https://idris2.readthedocs.io/en/latest/faq/faq.html#does-idris-have-universe-polymorphism-what-is-the-type-of-type): "Idris 2目前实现 Type:Type。别担心，不会永远这样的！"😂

> 比如 Semigroup Int 你觉得里面的操作是加法还是乘法呀

这确实是个纠结的地方, idris的方法是允许[命名实现](https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html#named-implementations), 正好他的例子里也说的是数字是加法半群还是乘法半群的问题...

我去查了一下arend才知道原来也是个语言, 看起来想法也差不多..

> 讲讲？

哦哦我仔细看了一下大部分看懂了.. 刚才看到`====>`在想这是啥操作, 原来是自定义中缀符.

```
data List (A : Type) : Type | nil | infixr :< A (List A)
```
这里面的`:<`是啥, 子类型吗?

**Comment by ice1000** [comment]
> 这确实是个纠结的地方, idris的方法是允许[命名实现](https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html#named-implementations), 正好他的例子里也说的是数字是加法半群还是乘法半群的问题...

还有一个问题就是 DT 里面 type alias 的问题。比如 `instance Fin (suc n) where` 这样的应该不应该允许。

> 我去查了一下arend才知道原来也是个语言, 看起来想法也差不多..

看起来差不多可能是因为早期 Aya 有点过度（并不是故意的）模仿 Arend，但我们现在已经几乎是截然不同的语言啦。

> 这里面的:<是啥, 子类型吗?

是构造器的名字~ 你看后面的模式匹配就懂了。

**Comment by ice1000** [comment]
我们对中缀运算符没有 Haskell 那样的限制。我们还有左缀和右缀运算符，比 Haskell 高级。左缀运算符和函数应用不一样的地方在于 `f f a` 解析为 `f(f, a)` 而 `~ ~ a` 解析为 `~ (~ a)`

**Comment by ice1000** [comment]
运算符的解析是 @imkiva 一人完成。还有类型检查的顺序自动生成也是。

**Comment by lsby** [comment]
> 比如 instance Fin (suc n) where 这样的应该不应该允许。

没懂是啥意思, Fin是个类型, 不是个类型类鸭?

> 是构造器的名字~ 你看后面的模式匹配就懂了。

原来如此, 看懂了, 原来中缀符号的声明可以混在一起写.

那么FFI有吗, 还有后端...可以编译到js吗(
要用起来可能还要有record...record好像挺麻烦的, idris里我就没搞明白要怎么动态的取record的值(比如把一个record的所有key转换为`List String`), purescript里用一套复杂的类型类可以凑出来...
大大加油! 差不多能用了我就来体验一下🤩

**Comment by ice1000** [comment]
> 没懂是啥意思, Fin是个类型, 不是个类型类鸭?

写错了，应该是 instance X (Fin x) where 然后 X 是 class

> 原来如此, 看懂了, 原来中缀符号的声明可以混在一起写.

对，我觉得这严格强于 Haskell 那个语法。

> 那么FFI有吗, 还有后端...可以编译到js吗(

你来写！我们打磨这个类型系统打磨了两年了，等一切基本稳定后再继续做编译、后端等。我们可是打算部分自举的。

> 要用起来可能还要有record...record好像挺麻烦的, idris里我就没搞明白要怎么动态的取record的值(比如把一个record的所有key转换为`List String`), purescript里用一套复杂的类型类可以凑出来...

Record 有，但我觉得应该直接实现 class，然后再把 record 做成 class 的特殊情况。

**Comment by ice1000** [comment]
打算删了现在的 record 从头再来

**Comment by lsby** [comment]
> 写错了，应该是 instance X (Fin x) where 然后 X 是 class

啊, idris2试了一下, 这个是可以的, 不知道是不是我理解错了:
```haskell
module Main

data AAA = A1
data BBB a = B1 a

interface CCC a where
interface DDD (a : Type -> Type) where

CCC AAA where
DDD BBB where

f1 : CCC a => a -> String
f1 _ = "f1"

f2 : DDD a => a String -> String
f2 _ = "f2"

d1 = f1 A1
d2 = f2 (B1 "aaa")

main : IO ()
main = printLn $ d1 ++ d2 -- 结果是"f1f2"
```

> 你来写！我们打磨这个类型系统打磨了两年了，等一切基本稳定后再继续做编译、后端等。我们可是打算部分自举的。

hhhhh好! 之后我看下, 说不定我也能写点w

**Comment by ice1000** [comment]
来得正好 https://www.aya-prover.org/guide/haskeller-tutorial.html

**Comment by lsby** [comment]
好耶, 这看起来是个简单易懂的教程了, 我来试试w

**Comment by ice1000** [comment]
刷新一下，我刚加了一坨

**Comment by lsby** [comment]
草

```
> :l src\\Main.aya
🐂🍺
```

**Comment by lsby** [comment]
好像不是很妙

aya.json:
```
{
  "ayaVersion": "0.23",
  "name": "aya_test",
  "version": "0.0.1",
  "dependency": {}
}

```

src/Main.aya:
```
data Nat | zero | suc Nat

def infixl <+> Nat Nat : Nat
| 0, n => n
| suc m, n => suc (m <+> n)
```

```
> :l src\\Main.aya
In file C:\Users\hbyBy\Desktop\aya_test\src\Main.aya:5:2 ->

  3 | def infixl <+> Nat Nat : Nat
  4 | | 0, n => n
  5 | | suc m, n => suc (m <+> n)
        ^-^

Error: Unknown constructor
         suc

Resolving interrupted due to:
1 error(s), 0 warning(s).
```

用的是最新的windows [nightly](https://github.com/aya-prover/aya-dev/releases/tag/nightly-build)

**Comment by ice1000** [comment]
`open data`

**Comment by ice1000** [comment]
文字描述里说了的。我等会在文章里加上。

**Comment by ice1000** [comment]
感谢指正！

**Comment by ice1000** [comment]
> 草
> 
> ```
> > :l src\\Main.aya
> 🐂🍺
> ```

试试触发个报错

**Comment by ice1000** [comment]
IIRC 它会给你一个 🔨

**Comment by ice1000** [comment]
原本想输出 🌶🐔 的，但是早期 Windows terminal 对 🌶 这个 emoji 的支持很差，所以就放弃了这个想法。

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/202595882-e4374e9b-631e-477a-ba72-80bfdfdb2049.png)

现在依然是如此。

**Comment by lsby** [comment]
> IIRC 它会给你一个 🔨

hhhhhh是的, 刚才报错就看到了, 没复制上.

> 原本想输出 🌶🐔 的

hhhhhhhhhhhhhh
